name: Fork News
description: Keeps your fork up to date
author: Vitor Nunes
branding:
  icon: 'calendar'  
  color: 'blue'
inputs:
  user-email:
    description: 'email.'
    required: true
  user-name:
    description: 'name.'
    required: true
  access-token:
    description: 'Access token with the repo scope used to access the repository and open PRs.'
    required: true
  from-repository:
    description: 'Path to the upstream repository (owner/repository). Use the value fork-upstream to point it to the default upstream.'
    required: false
    default: fork-upstream
  to-branch:
    description: 'Target branch of the pull request.'
    required: false
    default: main
  from-branch:
    description: 'Base branch of the pull request.'
    required: false
    default: main
  pr-title:
    description: 'Message used as the PR title.'
    required: false
    default: Fork News - Updates from the parent repository
  pr-description:
    description: 'Message used as the PR body'
    required: false
    default: Here are the latest changes from the parent repository.

outputs:
  has_new_commits:
    description: 'true when new commits were included in this sync'
    value: ${{ steps.git-step.outputs.has_new_commits }}

runs:
  using: composite
  steps:
    - id: update-step
      shell: bash
      run: >- 
        ${{ github.action_path }}/update_step.sh 
    - id: config
      shell: bash
      run: |
        git config --global user.email "${{ inputs.user-email }}"
        git config --global user.name "${{ inputs.user-name }}"
    - id: git-step
      shell: bash
      run: >-
        ${{ github.action_path }}/git_step.sh 
        ${{ inputs.access-token }} 
        ${{ github.repository }}
        ${{ inputs.to-branch }}
        ${{ inputs.from-repository }}
        ${{ inputs.from-branch }}
        ${{ github.actor }}
    - id: pr-step
      shell: bash
      run: >-
        ${{ github.action_path }}/pr_step.sh 
        ${{ inputs.access-token }} 
        ${{ github.repository }} 
        ${{ steps.git-step.outputs.fork-news-branch }}
        ${{ inputs.to-branch }}
        "${{ inputs.pr-title }}"
        "${{ inputs.pr-description }}"